# 📄 Datei: agents.rules.yaml
# 🔧 Zweck: Regelwerk für die MCP-Struktur
# 👤 Autor: MINT-RESEARCH
# 📅 Erstellt: 2025-04-13
# 📘 Gültigkeit: required
# 🧱 Version: 1.0.0

agents:
  mcp_agent_interaction_engine:
    description: Zentrale Dialogsteuerung
    type: mcp_agent
    singleton: true
    required: true
    capabilities:
      - dialog_management
      - user_input_handling
    access_level: full