# 📄 Datei: logging.rules.yaml
# 🔧 Zweck: Regelwerk für die MCP-Struktur
# 👤 Autor: MINT-RESEARCH
# 📅 Erstellt: 2025-04-13
# 📘 Gültigkeit: required
# 🧱 Version: 1.0.0

logging:
  structure:
    base_dir: logs/
    categories:
      - system
      - interaction
      - error
      - agent
      - tool
  format:
    type: jsonl
    timestamp: iso8601
  rotation:
    policy: daily
    max_file_size: 10MB
    retention_days: 30
    compress_after_days: 7
