# 📄 Datei: permissions.rules.yaml
# 🔧 Zweck: Regelwerk für die MCP-Struktur
# 👤 Autor: MINT-RESEARCH
# 📅 Erstellt: 2025-04-13
# 📘 Gültigkeit: required
# 🧱 Version: 1.0.0

permissions:
  default:
    access: restricted
  mcp_agent_interaction_engine:
    access: full
  mcp_host_memory_store:
    access: write
  mcp_tool_executor:
    access: read