# 📄 Datei: docker-compose.yaml
# 🔧 Zweck: Komponente des MCP-Systems
# 👤 Autor: MINT-RESEARCH
# 📅 Erstellt: 2025-04-13
# 📘 Gültigkeit: required
# 🧱 Version: 1.0.0

version: '3.8'

services:
  interaction_engine:
    build: ./mcp_units/mcp_agent_interaction_engine
    container_name: interaction_engine
    ports:
      - "8000:5000"
    environment:
      - PORT=5000

  executor:
    build: ./mcp_units/mcp_tool_executor
    container_name: executor
    ports:
      - "8001:5000"
    environment:
      - PORT=5000

  memory_store:
    build: ./mcp_units/mcp_host_memory_store
    container_name: memory_store
    ports:
      - "8002:5000"
    environment:
      - PORT=5000

  llm_infer:
    build: ./mcp_units/mcp_host_llm_infer
    container_name: llm_infer
    ports:
      - "8003:5000"
    environment:
      - PORT=5000
      
  mcp_gateway:
    build: ./mcp_units/mcp_agent_interaction_engine
    container_name: mcp_gateway
    ports:
      - "9000:9000"
    environment:
      - PORT=9000
    command: python api_gateway.py
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/mcp/status"]
      interval: 10s
      timeout: 5s
      retries: 5
