# 📄 Datei: memory.policy.yaml
# 🔧 Zweck: Richtlinien für die MCP-Komponenten
# 👤 Autor: MINT-RESEARCH
# 📅 Erstellt: 2025-04-13
# 📘 Gültigkeit: required
# 🧱 Version: 1.0.0

policy_id: memory_default
description: Standard-Policy für Memory-Verwaltung in einem Einagentensystem.
version: 1.0.0

terms:
  - id: MT001
    name: "Speicherrichtlinien"
    description: "Richtlinien für die Speicherverwaltung im MCP-System"
    content: "Diese Richtlinie definiert die Standardverhaltensweise für die Speicherverwaltung im MCP-System."
    last_updated: 2025-04-13
    acceptance_required: true

storage:
  persistence: true
  auto_load: true
  file_path: runtime_state/state_memory.json

access_control:
  allow_external_read: true
  allow_external_write: false
  whitelist_units:
    - mcp_agent_interaction_engine

expiration:
  default_ttl: 3600         # in Sekunden (1h)
  cleanup_on_startup: true
  notify_on_expiry: false

rules:
  - id: M001
    description: Memory-Einträge dürfen nur vom Hauptagenten geschrieben werden.
    active: true
  - id: M002
    description: Persistenz ist standardmäßig aktiviert.
    active: true